export const UPDATE_AGE = "UPDATE_AGE";
export const UPDATE_SEX = "UPDATE_SEX";
export const UPDATE_HEIGHT = "UPDATE_HEIGHT";
export const UPDATE_WEIGHT = "UPDATE_WEIGHT";
export const UPDATE_ACTIVITY_LEVEL = "UPDATE_ACTIVITY_LEVEL";
export const UPDATE_DESIRED_DIFFICULTY = "UPDATE_DESIRED_DIFFICULTY";
export const UPDATE_FITNESS_GOALS = "UPDATE_FITNESS_GOALS";
export const UPDATE_APP_FIRST_TIME_USAGE = "UPDATE_APP_FIRST_TIME_USAGE";
