export const UPDATE_KEYBOARD = "UPDATE_KEYBOARD";
export const UPDATE_EMAIL = "UPDATE_EMAIL";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_FIRST_NAME = "UPDATE_FIRST_NAME";
export const UPDATE_LAST_NAME = "UPDATE_LAST_NAME";
export const UPDATE_HEIGHT = "UPDATE_HEIGHT";
export const SIGN_IN_USER = "SIGN_IN_USER";
export const UPDATE_SESSION_ID = "UPDATE_SESSION_ID";
